[package]
name = "duex_runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
duex_lexer = { path = "../duex_lexer" }
duex_parser = { path = "../duex_parser" }
duex_syntax = { path = "../duex_syntax" }